server:
  port: 6004

spring:
  application:
    name: auth-base
  cloud:
    nacos:
      discovery:
        server-addr: http://47.103.140.52:8848
        namespace: 8202bec7-684e-4c5a-8791-a18dfd331a83
        group: auth-tutorial
        username: nacos
        password: nacos9Ij991uDDKK
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        username: ${spring.cloud.nacos.discovery.username}
        password: ${spring.cloud.nacos.discovery.password}

# 添加 spring.config.import 属性
  config:
    import: nacos:auth-base


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth-tutorial?autosave=conservative
    username: loong
    password: loong
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 1200
      login-timeout: 1200
      validation-timeout: 1000
      initialization-fail-timeout: 200
      auto-commit: true

  profiles:
    active: dev

